name: tag latest
on:
    release:
        types: [published, edited]

jobs:
    latest:
        runs-on: ubuntu-latest
        steps:
            - name: Run latest-tag
              uses: EndBug/latest-tag@latest
