name: bump version
on:
    push:
        branches:  [main]

jobs:
    increment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.17.2
              env:
                  WITH_V: true
                  DEFAULT_BUMP: minor
                  RELEASE_BRANCHES: main
